apiVersion: external-secrets.io/v1beta1
kind: ExternalSecretStore
metadata:
  name: aws-secrets-store
  namespace: external-secrets # Must be the same namespace where ESO is installed
spec:
  provider:
    aws:
      region: <your-aws-region> # e.g., us-east-1
      service: SecretsManager
      auth:
        # Method 1: Using IAM roles for service accounts (recommended)
        iam:
          roleArn: <your-iam-role-arn> # ARN of the IAM role attached to your Kubernetes nodes

        # Method 2: Using AWS credentials (less recommended for production)
        # accessKeyID: <your-aws-access-key-id>
        # secretAccessKey: <your-aws-secret-access-key>